### ISSUE TITLE
Site Initialization To-Do List

### ISSUE THREAD

**Issue by ayogasekaram** [insightsengineering/table.drawing.research#2]
House Keeping:

- [x] renv
- [x] use development version of gt 

 Outputs:
- [x] #7
- [x] #6
- [x] #5
- [x] #3
- [x] #4

Notes:

- save the gt object somewhere in the repo
- render it as a page as a quarto document in isolation

in the quarto.yml, don't render quarto files, 
```
project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides-gtsummary/[0-9]*.qmd"
```
